name: snapshot
on: [push]
jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install
      - run: yarn test:snapshot:ci
        continue-on-error: true
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: snapshot-diff
          path: packages/component/src/**/__snapshots__/__diff_output__/*